Add new FAQ to README in case users cannot see results due to the default `filter_mode`
EPMatt/reviewdog-action-tsc pull request #46
Opened 2022-02-13 12:43 UTC by jihoon416

### Summary
This PR adds a new FAQ for users having trouble with seeing the results.
closes #39 

### Details
The newly added FAQ looks like below.
```markdown
### Why can't I see the results?
Try looking into the `filter_mode` options explained [here](https://github.com/reviewdog/reviewdog#filter-mode). TypeScript errors will sometimes appear in lines or files that weren't modified by the commit the workflow run is associated with, which instead get filtered with the default `added` option.
```

2022-02-15 22:07 UTC, EPMatt requested changes
Hi @jihoon416,

thank you so much for your contribution!
I'm opening this review just to make you experiment this really useful GItHub feature, which allows code contributors to discuss and request changes before a PR gets merged. I requested a small change in your commit. :) 

Moreover, I'd like to inform you about another useful GitHub feature which many newcomers don't know: adding `closes` followed by # and the issue number to the first PR comment links an issue to the PR. This means the issue is automatically closed as soon as the PR gets merged in the `main` branch.
You can read more about this feature [here](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue). Try to add `closes #39` to your opening comment and notice the issue being linked to the PR. :) 

Thanks again for your time!

2022-02-19 15:33 UTC, jihoon416 commented on README.md
> +Try looking into the `filter_mode` options explained [here](https://github.com/reviewdog/reviewdog#filter-mode). Typescript errors will sometimes appear in lines or files that weren't modified by the
Ohh haha thanks for pointing it out. I actually realized the same thing a few weeks ago and tried to use the official term if possible but seems habits die hard. 😅

2022-02-19 15:44 UTC, jihoon416 commented
Hello again @EPMatt

Thanks for that useful tip! Really surprised to know GitHub had this cool automated feature. I'm gaining a lot of helpful experience by contributing to your repo. Thank you for your kind and detailed explanation!

2022-02-21 21:15 UTC, EPMatt approved these changes

2022-02-21 21:27 UTC, EPMatt commented
Hi @jihoon416,

>  I'm gaining a lot of helpful experience by contributing to your repo. Thank you for your kind and detailed explanation!

You're welcome! I'm so glad that my help allowed you to make your first contributions here. Seeing new contributors starting their journey into open source is always a great pleasure for me, and I'll always be happy to help people contributing to the projects they truly love. 😄 

Thank you for looking into my suggestions. I'll now merge this PR into `main`, effectively adding your contribution to the repo's README.

Thank you again for dedicating your precious time to this project, and welcome to the open source community! 🎉

2022-02-21 21:28 UTC, merged